# Generated by Django 5.1 on 2024-08-28 15:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagn', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagn',
            name='disk_load',
        ),
        migrations.RemoveField(
            model_name='diagn',
            name='gpu_load',
        ),
        migrations.RemoveField(
            model_name='diagn',
            name='proces_load',
        ),
        migrations.AddField(
            model_name='diagn',
            name='date_comit',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='diagn',
            name='time_comit',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
